; generated by PrusaSlicer 2.8.0 on 2024-09-21 at 14:29:13 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S2000 T1500 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X10.00 Y10.00 Z0.20 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

; printing object file1.stl id:0 copy 0
; stop printing object file1.stl id:0 copy 0

;TYPE:Custom
M862.3 P "MK2.5" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.11.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
M73 P7 R0

G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-.8 F2100
M73 P11 R0
G1 Z.6 F720
G1 X118.574 Y103.181 F10800
G1 Z.2 F720
M73 P13 R0
G1 E.8 F2100
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X119.663 Y101.985 E.05072
G1 X121.5 Y101.43 E.06017
G1 X128.5 Y101.43 E.21948
G1 X130.069 Y101.824 E.05072
M73 P14 R0
G1 X131.265 Y102.913 E.05072
G1 X131.82 Y104.75 E.06017
M73 P15 R0
G1 X131.82 Y105.25 E.01568
G1 X131.426 Y106.819 E.05072
G1 X130.337 Y108.015 E.05072
G1 X128.5 Y108.57 E.06017
G1 X121.5 Y108.57 E.21948
M73 P16 R0
G1 X119.931 Y108.176 E.05072
M73 P17 R0
G1 X118.735 Y107.087 E.05072
G1 X118.18 Y105.25 E.06017
G1 X118.18 Y104.75 E.01568
G1 X118.56 Y103.24 E.04882
M204 S1000
G1 X118.56 Y103.24 F10800
G1 X118.935 Y103.34
M204 S800
G1 F900
M73 P18 R0
G1 X118.951 Y103.28 E.00195
G1 X120.025 Y102.204 E.04767
G1 X121.5 Y101.807 E.04789
G1 X128.5 Y101.807 E.21948
G1 X129.97 Y102.201 E.04772
M73 P19 R0
G1 X131.046 Y103.275 E.04767
G1 X131.443 Y104.75 E.04789
G1 X131.443 Y105.25 E.01568
G1 X131.049 Y106.72 E.04772
G1 X129.975 Y107.796 E.04767
M73 P20 R0
G1 X128.5 Y108.193 E.04789
G1 X121.5 Y108.193 E.21948
G1 X120.03 Y107.8 E.04771
M73 P21 R0
G1 X118.954 Y106.725 E.04769
G1 X118.557 Y105.25 E.04789
G1 X118.557 Y104.75 E.01568
G1 X118.919 Y103.398 E.04388
M73 P22 R0
M204 S1000
G1 X118.919 Y103.398 F10800
G1 X119.292 Y103.505
M204 S800
G1 F900
G1 X119.327 Y103.387 E.00386
G1 X120.383 Y102.44 E.04447
G1 X121.5 Y102.184 E.03593
G1 X128.5 Y102.184 E.21948
G1 X129.863 Y102.577 E.04448
M73 P23 R0
G1 X130.81 Y103.633 E.04447
G1 X131.066 Y104.75 E.03593
G1 X131.066 Y105.25 E.01568
G1 X130.673 Y106.613 E.04448
M73 P24 R0
G1 X129.617 Y107.56 E.04447
G1 X128.5 Y107.816 E.03593
G1 X121.5 Y107.816 E.21948
G1 X120.137 Y107.423 E.04448
M73 P25 R0
G1 X119.19 Y106.367 E.04447
G1 X118.934 Y105.25 E.03593
G1 X118.934 Y104.75 E.01568
G1 X119.276 Y103.563 E.03873
M73 P26 R0
M204 S1000
G1 X119.276 Y103.563 F10800
G1 X119.647 Y103.679
M204 S800
G1 F900
G1 X119.702 Y103.502 E.00581
G1 X120.735 Y102.699 E.04102
G1 X121.5 Y102.561 E.02437
G1 X128.5 Y102.561 E.21948
G1 X129.748 Y102.952 E.04101
M73 P27 R0
G1 X130.551 Y103.985 E.04102
G1 X130.689 Y104.75 E.02437
G1 X130.689 Y105.25 E.01568
G1 X130.298 Y106.498 E.04101
G1 X129.265 Y107.301 E.04102
M73 P28 R0
G1 X128.5 Y107.439 E.02437
G1 X121.5 Y107.439 E.21948
G1 X120.252 Y107.048 E.04101
M73 P29 R0
G1 X119.449 Y106.015 E.04102
G1 X119.311 Y105.25 E.02437
G1 X119.311 Y104.75 E.01568
G1 X119.629 Y103.736 E.03332
M204 S1000
;WIPE_START
G1 F8640
G1 X119.647 Y103.679 E-.0138
G1 X119.702 Y103.502 E-.0428
G1 X120.735 Y102.699 E-.30211
G1 X121.5 Y102.561 E-.17949
G1 X122.634 Y102.561 E-.2618
;WIPE_END
G1 Z.6 F720
M73 P30 R0
; printing object file1.stl id:0 copy 0
G1 X121.75 Y105 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.50001
G1 F900
G1 X128.25 Y105 E.24705
M204 S1000
M106 S84.15
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4


;WIPE_START
G1 F8640
M73 P31 R0
G1 X124.785 Y105 E-.8
;WIPE_END
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.4
;CURRENT_Z: 0.4
M104 S210 ; set temperature
; stop printing object file1.stl id:0 copy 0
G1 Z.8
G1 X124.785 Y101.43 F10800
G1 Z.4 F720
G1 E.8 F2100
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X128.5 Y101.43 E.11648
G1 X130.069 Y101.824 E.05072
M73 P32 R0
G1 X131.265 Y102.913 E.05072
G1 X131.82 Y104.75 E.06017
G1 X131.82 Y105.25 E.01568
M73 P33 R0
G1 X131.426 Y106.819 E.05072
G1 X130.337 Y108.015 E.05072
G1 X128.5 Y108.57 E.06017
G1 X121.5 Y108.57 E.21948
G1 X119.931 Y108.176 E.05072
M73 P34 R0
G1 X118.735 Y107.087 E.05072
M73 P35 R0
G1 X118.18 Y105.25 E.06017
G1 X118.18 Y104.75 E.01568
G1 X118.574 Y103.181 E.05072
G1 X119.663 Y101.985 E.05072
G1 X121.5 Y101.43 E.06017
G1 X124.725 Y101.43 E.10112
M73 P36 R0
G1 X124.725 Y101.43 F10800
G1 X124.725 Y101.807
G1 F900
G1 X128.5 Y101.807 E.11836
G1 X129.97 Y102.201 E.04772
M73 P37 R0
G1 X131.046 Y103.275 E.04767
G1 X131.443 Y104.75 E.04789
G1 X131.443 Y105.25 E.01568
G1 X131.049 Y106.72 E.04772
G1 X129.975 Y107.796 E.04767
G1 X128.5 Y108.193 E.04789
M73 P38 R0
G1 X121.5 Y108.193 E.21948
G1 X120.03 Y107.8 E.04771
M73 P39 R0
G1 X118.954 Y106.725 E.04769
G1 X118.557 Y105.25 E.04789
G1 X118.557 Y104.75 E.01568
G1 X118.951 Y103.28 E.04772
G1 X120.025 Y102.204 E.04767
M73 P40 R0
G1 X121.5 Y101.807 E.04789
G1 X124.665 Y101.807 E.09924
G1 X124.665 Y101.807 F10800
G1 X124.665 Y102.184
G1 F900
G1 X128.5 Y102.184 E.12024
G1 X129.863 Y102.577 E.04448
M73 P41 R0
G1 X130.81 Y103.633 E.04447
G1 X131.066 Y104.75 E.03593
G1 X131.066 Y105.25 E.01568
G1 X130.673 Y106.613 E.04448
G1 X129.617 Y107.56 E.04447
M73 P42 R0
G1 X128.5 Y107.816 E.03593
G1 X121.5 Y107.816 E.21948
G1 X120.137 Y107.423 E.04448
M73 P43 R0
G1 X119.19 Y106.367 E.04447
G1 X118.934 Y105.25 E.03593
G1 X118.934 Y104.75 E.01568
G1 X119.327 Y103.387 E.04448
G1 X120.383 Y102.44 E.04447
M73 P44 R0
G1 X121.5 Y102.184 E.03593
G1 X124.605 Y102.184 E.09736
G1 X124.605 Y102.184 F10800
G1 X124.605 Y102.561
G1 F900
G1 X128.5 Y102.561 E.12212
G1 X129.748 Y102.952 E.04101
M73 P45 R0
G1 X130.551 Y103.985 E.04102
G1 X130.689 Y104.75 E.02437
G1 X130.689 Y105.25 E.01568
G1 X130.298 Y106.498 E.04101
G1 X129.265 Y107.301 E.04102
G1 X128.5 Y107.439 E.02437
M73 P46 R0
G1 X121.5 Y107.439 E.21948
G1 X120.252 Y107.048 E.04101
M73 P47 R0
G1 X119.449 Y106.015 E.04102
G1 X119.311 Y105.25 E.02437
G1 X119.311 Y104.75 E.01568
G1 X119.702 Y103.502 E.04101
G1 X120.735 Y102.699 E.04102
G1 X121.5 Y102.561 E.02437
G1 X124.545 Y102.561 E.09547
M73 P48 R0
;WIPE_START
G1 F8640
G1 X124.605 Y102.561 E-.01385
G1 X128.01 Y102.561 E-.78615
;WIPE_END
G1 Z.8 F720
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
G1 Z.4 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.50001
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
M106 S170.85
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.6


;WIPE_START
G1 F8640
M73 P49 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z.6 F720
M73 P50 R0
;AFTER_LAYER_CHANGE
;0.6
;CURRENT_Z: 0.6
; stop printing object file1.stl id:0 copy 0
G1 Z1
G1 X125.215 Y101.43 F10800
G1 Z.6 F720
G1 E.8 F2100
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X128.5 Y101.43 E.103
G1 X130.069 Y101.824 E.05072
M73 P51 R0
G1 X131.265 Y102.913 E.05072
G1 X131.82 Y104.75 E.06017
G1 X131.82 Y105.25 E.01568
G1 X131.426 Y106.819 E.05072
G1 X130.337 Y108.015 E.05072
G1 X128.5 Y108.57 E.06017
M73 P52 R0
G1 X121.5 Y108.57 E.21948
G1 X119.931 Y108.176 E.05072
M73 P53 R0
G1 X118.735 Y107.087 E.05072
G1 X118.18 Y105.25 E.06017
G1 X118.18 Y104.75 E.01568
G1 X118.574 Y103.181 E.05072
M73 P54 R0
G1 X119.663 Y101.985 E.05072
G1 X121.5 Y101.43 E.06017
G1 X125.155 Y101.43 E.1146
G1 X125.155 Y101.43 F10800
M73 P55 R0
G1 X125.155 Y101.807
G1 F900
G1 X128.5 Y101.807 E.10488
G1 X129.97 Y102.201 E.04772
G1 X131.046 Y103.275 E.04767
G1 X131.443 Y104.75 E.04789
G1 X131.443 Y105.25 E.01568
M73 P56 R0
G1 X131.049 Y106.72 E.04772
G1 X129.975 Y107.796 E.04767
G1 X128.5 Y108.193 E.04789
G1 X121.5 Y108.193 E.21948
G1 X120.03 Y107.8 E.04771
M73 P57 R0
G1 X118.954 Y106.725 E.04769
G1 X118.557 Y105.25 E.04789
M73 P58 R0
G1 X118.557 Y104.75 E.01568
G1 X118.951 Y103.28 E.04772
G1 X120.025 Y102.204 E.04767
G1 X121.5 Y101.807 E.04789
G1 X125.095 Y101.807 E.11272
G1 X125.095 Y101.807 F10800
M73 P59 R0
G1 X125.095 Y102.184
G1 F900
G1 X128.5 Y102.184 E.10676
G1 X129.863 Y102.577 E.04448
G1 X130.81 Y103.633 E.04447
M73 P60 R0
G1 X131.066 Y104.75 E.03593
G1 X131.066 Y105.25 E.01568
G1 X130.673 Y106.613 E.04448
G1 X129.617 Y107.56 E.04447
G1 X128.5 Y107.816 E.03593
G1 X121.5 Y107.816 E.21948
G1 X120.137 Y107.423 E.04448
M73 P61 R0
G1 X119.19 Y106.367 E.04447
M73 P62 R0
G1 X118.934 Y105.25 E.03593
G1 X118.934 Y104.75 E.01568
G1 X119.327 Y103.387 E.04448
G1 X120.383 Y102.44 E.04447
G1 X121.5 Y102.184 E.03593
G1 X125.035 Y102.184 E.11084
G1 X125.035 Y102.184 F10800
M73 P63 R0
G1 X125.035 Y102.561
G1 F900
G1 X128.5 Y102.561 E.10864
G1 X129.748 Y102.952 E.04101
G1 X130.551 Y103.985 E.04102
G1 X130.689 Y104.75 E.02437
M73 P64 R0
G1 X130.689 Y105.25 E.01568
G1 X130.298 Y106.498 E.04101
G1 X129.265 Y107.301 E.04102
G1 X128.5 Y107.439 E.02437
G1 X121.5 Y107.439 E.21948
G1 X120.252 Y107.048 E.04101
M73 P65 R0
G1 X119.449 Y106.015 E.04102
G1 X119.311 Y105.25 E.02437
G1 X119.311 Y104.75 E.01568
M73 P66 R0
G1 X119.702 Y103.502 E.04101
G1 X120.735 Y102.699 E.04102
G1 X121.5 Y102.561 E.02437
G1 X124.975 Y102.561 E.10896
;WIPE_START
G1 F8640
M73 P67 R0
G1 X125.035 Y102.561 E-.01385
G1 X128.44 Y102.561 E-.78615
;WIPE_END
G1 Z1 F720
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
G1 Z.6 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.50001
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
M106 S255
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8


;WIPE_START
G1 F8640
M73 P68 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z.8 F720
;AFTER_LAYER_CHANGE
;0.8
;CURRENT_Z: 0.8
G1 Z1.2
G1 X128.25 Y105 F10800
G1 Z.8 F720
G1 E.8 F2100
M73 P69 R0
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1


;WIPE_START
G1 F8640
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z1 F720
M73 P70 R0
;AFTER_LAYER_CHANGE
;1
;CURRENT_Z: 1
G1 Z1.4
G1 X128.25 Y105 F10800
G1 Z1 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.2


;WIPE_START
G1 F8640
M73 P71 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z1.2 F720
;AFTER_LAYER_CHANGE
;1.2
;CURRENT_Z: 1.2
G1 Z1.6
G1 X128.25 Y105 F10800
G1 Z1.2 F720
M73 P72 R0
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.4


;WIPE_START
G1 F8640
M73 P73 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z1.4 F720
;AFTER_LAYER_CHANGE
;1.4
;CURRENT_Z: 1.4
G1 Z1.8
G1 X128.25 Y105 F10800
G1 Z1.4 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.6


;WIPE_START
G1 F8640
M73 P74 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z1.6 F720
;AFTER_LAYER_CHANGE
;1.6
;CURRENT_Z: 1.6
G1 Z2
G1 X128.25 Y105 F10800
G1 Z1.6 F720
M73 P75 R0
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.8


;WIPE_START
G1 F8640
M73 P76 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z1.8 F720
;AFTER_LAYER_CHANGE
;1.8
;CURRENT_Z: 1.8
G1 Z2.2
G1 X128.25 Y105 F10800
G1 Z1.8 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2


;WIPE_START
G1 F8640
M73 P77 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z2 F720
;AFTER_LAYER_CHANGE
;2
;CURRENT_Z: 2
G1 Z2.4
G1 X128.25 Y105 F10800
M73 P78 R0
G1 Z2 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.2


;WIPE_START
G1 F8640
M73 P79 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z2.2 F720
;AFTER_LAYER_CHANGE
;2.2
;CURRENT_Z: 2.2
G1 Z2.6
G1 X128.25 Y105 F10800
G1 Z2.2 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.4


;WIPE_START
G1 F8640
M73 P80 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z2.4 F720
;AFTER_LAYER_CHANGE
;2.4
;CURRENT_Z: 2.4
G1 Z2.8
M73 P81 R0
G1 X128.25 Y105 F10800
G1 Z2.4 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.6


;WIPE_START
G1 F8640
M73 P82 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z2.6 F720
;AFTER_LAYER_CHANGE
;2.6
;CURRENT_Z: 2.6
G1 Z3
G1 X128.25 Y105 F10800
G1 Z2.6 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.8


;WIPE_START
G1 F8640
M73 P83 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z2.8 F720
M73 P84 R0
;AFTER_LAYER_CHANGE
;2.8
;CURRENT_Z: 2.8
G1 Z3.2
G1 X128.25 Y105 F10800
G1 Z2.8 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;3


;WIPE_START
G1 F8640
M73 P85 R0
G1 X125.215 Y105 E-.8
;WIPE_END
G1 Z3 F720
;AFTER_LAYER_CHANGE
;3
;CURRENT_Z: 3
G1 Z3.4
G1 X128.25 Y105 F10800
G1 Z3 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24705
M204 S1000
; stop printing object file1.stl id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
M73 P86 R0
G1 X125.215 Y105 E-.8
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z4 F720 ; Move print head up
M73 P87 R0
G1 X0 Y200 F3600 ; park
G1 Z52 F720 ; Move print head further up
M73 P92 R0
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; objects_info = {"objects":[{"name":"file1.stl id:0 copy 0","polygon":[[128.500,105.250],[121.500,105.250],[121.500,104.750],[128.500,104.750]]}]}
; filament used [mm] = 37.26
; filament used [cm3] = 0.09
; filament used [g] = 0.11
; filament cost = 0.00
; total filament used [g] = 0.11
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 53s
; estimated first layer printing time (normal mode) = 17s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; colorprint_heights = 
; compatible_printers_condition = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK2[^.].*/ and nozzle_diameter[0]==0.4"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm OPTIMAL
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM900 K0 ; reset LA\nM84 ; disable motors
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 40
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_speed = nil
; filament_settings_id = "Generic PLA"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filament_wipe = nil
; fill_angle = 45
; fill_density = 20%
; fill_pattern = cubic
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; idle_temperature = nil
; infill_acceleration = 2000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 60
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\n;CURRENT_Z: [layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 10000
; machine_max_acceleration_extruding = 2000
; machine_max_acceleration_retracting = 1500
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000
; machine_max_acceleration_y = 9000
; machine_max_acceleration_z = 500
; machine_max_feedrate_e = 120
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 4.5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 200
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 50
; perimeters = 2
; physical_printer_settings_id = 
; post_process = ./post_process.py
; prefer_clockwise_movements = 0
; print_settings_id = 0.20mm NORMAL
; printer_model = MK2.5
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK2\n
; printer_settings_id = Original Prusa i3 MK2.5
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 199
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 50
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.11.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
M84 ; disable motors
