; generated by PrusaSlicer 2.5.0+linux-x64-GTK3 on 2022-09-09 at 20:31:14 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P2000 R1500 T2000 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X10.00 Y10.00 Z0.20 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK2.5" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.11.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line

G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P7 R0
G1 E-.8 F2100
M73 P11 R0
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.2
;CURRENT_Z: 0.2
G1 X118.386 Y103.134 F10800
G1 Z.2 F720
M73 P13 R0
G1 E.8 F2100
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X119.48 Y101.881 E.05215
G1 X121.5 Y101.242 E.06643
G1 X128.5 Y101.242 E.21948
G1 X130.116 Y101.636 E.05215
M73 P14 R0
G1 X131.369 Y102.73 E.05215
G1 X132.008 Y104.75 E.06643
G1 X132.008 Y105.25 E.01568
M73 P15 R0
G1 X131.614 Y106.866 E.05215
G1 X130.52 Y108.119 E.05215
G1 X128.5 Y108.758 E.06643
G1 X121.5 Y108.758 E.21948
M73 P16 R0
G1 X119.884 Y108.364 E.05215
G1 X118.631 Y107.27 E.05215
M73 P17 R0
G1 X117.992 Y105.25 E.06643
G1 X117.992 Y104.75 E.01568
G1 X118.372 Y103.192 E.05027
M204 S1000
G1 X118.747 Y103.29 F10800
M204 S800
G1 F900
G1 X118.762 Y103.23 E.00193
G1 X119.844 Y102.092 E.04923
G1 X121.5 Y101.619 E.054
M73 P18 R0
G1 X128.5 Y101.619 E.21948
G1 X130.02 Y102.012 E.04923
M73 P19 R0
G1 X131.158 Y103.094 E.04923
G1 X131.631 Y104.75 E.054
G1 X131.631 Y105.25 E.01568
G1 X131.238 Y106.77 E.04923
G1 X130.156 Y107.908 E.04923
M73 P20 R0
G1 X128.5 Y108.381 E.054
G1 X121.5 Y108.381 E.21948
G1 X119.98 Y107.988 E.04923
M73 P21 R0
G1 X118.842 Y106.906 E.04923
G1 X118.369 Y105.25 E.054
G1 X118.369 Y104.75 E.01568
G1 X118.732 Y103.348 E.04542
M204 S1000
G1 X119.106 Y103.451 F10800
M204 S800
M73 P22 R0
G1 F900
G1 X119.139 Y103.333 E.00386
G1 X120.205 Y102.319 E.04612
G1 X121.5 Y101.996 E.04186
G1 X128.5 Y101.996 E.21948
G1 X129.917 Y102.389 E.04612
M73 P23 R0
G1 X130.931 Y103.455 E.04612
G1 X131.254 Y104.75 E.04186
G1 X131.254 Y105.25 E.01568
G1 X130.861 Y106.667 E.04612
M73 P24 R0
G1 X129.795 Y107.681 E.04612
G1 X128.5 Y108.004 E.04186
G1 X121.5 Y108.004 E.21948
G1 X120.083 Y107.611 E.04612
M73 P25 R0
G1 X119.069 Y106.545 E.04612
G1 X118.746 Y105.25 E.04186
G1 X118.746 Y104.75 E.01568
M73 P26 R0
G1 X119.09 Y103.509 E.04038
M204 S1000
G1 X119.461 Y103.62 F10800
M204 S800
G1 F900
G1 X119.515 Y103.443 E.00581
G1 X120.56 Y102.567 E.04278
G1 X121.5 Y102.373 E.03008
G1 X128.5 Y102.373 E.21948
G1 X129.807 Y102.765 E.04278
M73 P27 R0
G1 X130.683 Y103.81 E.04278
G1 X130.877 Y104.75 E.03008
G1 X130.877 Y105.25 E.01568
G1 X130.485 Y106.557 E.04278
G1 X129.44 Y107.433 E.04278
M73 P28 R0
G1 X128.5 Y107.627 E.03008
G1 X121.5 Y107.627 E.21948
G1 X120.193 Y107.235 E.04278
M73 P29 R0
G1 X119.317 Y106.19 E.04278
G1 X119.123 Y105.25 E.03008
G1 X119.123 Y104.75 E.01568
G1 X119.444 Y103.678 E.03509
M204 S1000
; printing object file1.stl id:0 copy 0
;WIPE_START
G1 F8640
M73 P30 R0
G1 X119.515 Y103.443 E-.05661
G1 X120.56 Y102.567 E-.31505
G1 X121.5 Y102.373 E-.22155
G1 X122.222 Y102.373 E-.16679
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
G1 X128.25 Y105 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.5
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
M106 S84.15
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4


;WIPE_START
G1 F8640
M73 P31 R0
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
;AFTER_LAYER_CHANGE
;0.4
;CURRENT_Z: 0.4
M104 S210 ; set temperature
G1 X125.041 Y108.758 F10800
G1 Z.4 F720
M73 P32 R0
G1 E.8 F2100
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X121.5 Y108.758 E.11104
G1 X119.884 Y108.364 E.05215
G1 X118.631 Y107.27 E.05215
G1 X117.992 Y105.25 E.06643
M73 P33 R0
G1 X117.992 Y104.75 E.01568
G1 X118.386 Y103.134 E.05215
G1 X119.48 Y101.881 E.05215
G1 X121.5 Y101.242 E.06643
G1 X128.5 Y101.242 E.21948
M73 P34 R0
G1 X130.116 Y101.636 E.05215
M73 P35 R0
G1 X131.369 Y102.73 E.05215
G1 X132.008 Y104.75 E.06643
G1 X132.008 Y105.25 E.01568
G1 X131.614 Y106.866 E.05215
G1 X130.52 Y108.119 E.05215
G1 X128.5 Y108.758 E.06643
M73 P36 R0
G1 X125.101 Y108.758 E.10656
G1 X125.101 Y108.381 F10800
G1 F900
G1 X121.5 Y108.381 E.11292
G1 X119.98 Y107.988 E.04923
M73 P37 R0
G1 X118.842 Y106.906 E.04923
G1 X118.369 Y105.25 E.054
G1 X118.369 Y104.75 E.01568
G1 X118.762 Y103.23 E.04923
M73 P38 R0
G1 X119.844 Y102.092 E.04923
G1 X121.5 Y101.619 E.054
G1 X128.5 Y101.619 E.21948
G1 X130.02 Y102.012 E.04923
M73 P39 R0
G1 X131.158 Y103.094 E.04923
G1 X131.631 Y104.75 E.054
G1 X131.631 Y105.25 E.01568
M73 P40 R0
G1 X131.238 Y106.77 E.04923
G1 X130.156 Y107.908 E.04923
G1 X128.5 Y108.381 E.054
G1 X125.161 Y108.381 E.10468
G1 X125.161 Y108.004 F10800
M73 P41 R0
G1 F900
G1 X121.5 Y108.004 E.1148
G1 X120.083 Y107.611 E.04612
G1 X119.069 Y106.545 E.04612
G1 X118.746 Y105.25 E.04186
M73 P42 R0
G1 X118.746 Y104.75 E.01568
G1 X119.139 Y103.333 E.04612
G1 X120.205 Y102.319 E.04612
G1 X121.5 Y101.996 E.04186
G1 X128.5 Y101.996 E.21948
G1 X129.917 Y102.389 E.04612
M73 P43 R0
G1 X130.931 Y103.455 E.04612
G1 X131.254 Y104.75 E.04186
M73 P44 R0
G1 X131.254 Y105.25 E.01568
G1 X130.861 Y106.667 E.04612
G1 X129.795 Y107.681 E.04612
G1 X128.5 Y108.004 E.04186
G1 X125.221 Y108.004 E.1028
G1 X125.221 Y107.627 F10800
M73 P45 R0
G1 F900
G1 X121.5 Y107.627 E.11668
G1 X120.193 Y107.235 E.04278
G1 X119.317 Y106.19 E.04278
G1 X119.123 Y105.25 E.03008
M73 P46 R0
G1 X119.123 Y104.75 E.01568
G1 X119.515 Y103.443 E.04278
G1 X120.56 Y102.567 E.04278
G1 X121.5 Y102.373 E.03008
G1 X128.5 Y102.373 E.21948
G1 X129.807 Y102.765 E.04278
M73 P47 R0
G1 X130.683 Y103.81 E.04278
G1 X130.877 Y104.75 E.03008
G1 X130.877 Y105.25 E.01568
M73 P48 R0
G1 X130.485 Y106.557 E.04278
G1 X129.44 Y107.433 E.04278
G1 X128.5 Y107.627 E.03008
G1 X125.281 Y107.627 E.10092
; printing object file1.stl id:0 copy 0
;WIPE_START
G1 F8640
M73 P49 R0
G1 X121.99 Y107.627 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.8 F720
G1 X128.25 Y105 F10800
G1 Z.4 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.5
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
M106 S170.85
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.6


;WIPE_START
G1 F8640
M73 P50 R0
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.8 F720
;AFTER_LAYER_CHANGE
;0.6
;CURRENT_Z: 0.6
G1 X125.041 Y108.758 F10800
G1 Z.6 F720
M73 P51 R0
G1 E.8 F2100
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X121.5 Y108.758 E.11104
G1 X119.884 Y108.364 E.05215
G1 X118.631 Y107.27 E.05215
G1 X117.992 Y105.25 E.06643
M73 P52 R0
G1 X117.992 Y104.75 E.01568
G1 X118.386 Y103.134 E.05215
G1 X119.48 Y101.881 E.05215
G1 X121.5 Y101.242 E.06643
G1 X128.5 Y101.242 E.21948
M73 P53 R0
G1 X130.116 Y101.636 E.05215
M73 P54 R0
G1 X131.369 Y102.73 E.05215
G1 X132.008 Y104.75 E.06643
G1 X132.008 Y105.25 E.01568
G1 X131.614 Y106.866 E.05215
G1 X130.52 Y108.119 E.05215
G1 X128.5 Y108.758 E.06643
M73 P55 R0
G1 X125.101 Y108.758 E.10656
G1 X125.101 Y108.381 F10800
G1 F900
G1 X121.5 Y108.381 E.11292
G1 X119.98 Y107.988 E.04923
M73 P56 R0
G1 X118.842 Y106.906 E.04923
G1 X118.369 Y105.25 E.054
G1 X118.369 Y104.75 E.01568
G1 X118.762 Y103.23 E.04923
M73 P57 R0
G1 X119.844 Y102.092 E.04923
G1 X121.5 Y101.619 E.054
G1 X128.5 Y101.619 E.21948
G1 X130.02 Y102.012 E.04923
M73 P58 R0
G1 X131.158 Y103.094 E.04923
G1 X131.631 Y104.75 E.054
G1 X131.631 Y105.25 E.01568
M73 P59 R0
G1 X131.238 Y106.77 E.04923
G1 X130.156 Y107.908 E.04923
G1 X128.5 Y108.381 E.054
G1 X125.161 Y108.381 E.10468
G1 X125.161 Y108.004 F10800
M73 P60 R0
G1 F900
G1 X121.5 Y108.004 E.1148
G1 X120.083 Y107.611 E.04612
G1 X119.069 Y106.545 E.04612
G1 X118.746 Y105.25 E.04186
M73 P61 R0
G1 X118.746 Y104.75 E.01568
G1 X119.139 Y103.333 E.04612
G1 X120.205 Y102.319 E.04612
G1 X121.5 Y101.996 E.04186
G1 X128.5 Y101.996 E.21948
G1 X129.917 Y102.389 E.04612
M73 P62 R0
G1 X130.931 Y103.455 E.04612
G1 X131.254 Y104.75 E.04186
M73 P63 R0
G1 X131.254 Y105.25 E.01568
G1 X130.861 Y106.667 E.04612
G1 X129.795 Y107.681 E.04612
G1 X128.5 Y108.004 E.04186
G1 X125.221 Y108.004 E.1028
G1 X125.221 Y107.627 F10800
M73 P64 R0
G1 F900
G1 X121.5 Y107.627 E.11668
G1 X120.193 Y107.235 E.04278
G1 X119.317 Y106.19 E.04278
G1 X119.123 Y105.25 E.03008
M73 P65 R0
G1 X119.123 Y104.75 E.01568
G1 X119.515 Y103.443 E.04278
G1 X120.56 Y102.567 E.04278
G1 X121.5 Y102.373 E.03008
G1 X128.5 Y102.373 E.21948
G1 X129.807 Y102.765 E.04278
M73 P66 R0
G1 X130.683 Y103.81 E.04278
G1 X130.877 Y104.75 E.03008
M73 P67 R0
G1 X130.877 Y105.25 E.01568
G1 X130.485 Y106.557 E.04278
G1 X129.44 Y107.433 E.04278
G1 X128.5 Y107.627 E.03008
G1 X125.281 Y107.627 E.10092
; printing object file1.stl id:0 copy 0
;WIPE_START
G1 F8640
M73 P68 R0
G1 X121.99 Y107.627 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z1 F720
G1 X121.75 Y105 F10800
G1 Z.6 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.5
G1 F900
G1 X128.25 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
M106 S255
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8


;WIPE_START
G1 F8640
M73 P69 R0
G1 X124.959 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z1 F720
;AFTER_LAYER_CHANGE
;0.8
;CURRENT_Z: 0.8
; printing object file1.stl id:0 copy 0
G1 X121.75 Y105 F10800
G1 Z.8 F720
M73 P70 R0
G1 E.8 F2100
M204 S800
G1 F900
G1 X128.25 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1


;WIPE_START
G1 F8640
G1 X124.959 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
M73 P71 R0
G1 Z1.2 F720
;AFTER_LAYER_CHANGE
;1
;CURRENT_Z: 1
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
G1 Z1 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.2


;WIPE_START
G1 F8640
M73 P72 R0
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z1.4 F720
;AFTER_LAYER_CHANGE
;1.2
;CURRENT_Z: 1.2
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
G1 Z1.2 F720
G1 E.8 F2100
M204 S800
M73 P73 R0
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.4


;WIPE_START
G1 F8640
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
M73 P74 R0
G1 Z1.6 F720
;AFTER_LAYER_CHANGE
;1.4
;CURRENT_Z: 1.4
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
G1 Z1.4 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.6


;WIPE_START
G1 F8640
M73 P75 R0
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z1.8 F720
;AFTER_LAYER_CHANGE
;1.6
;CURRENT_Z: 1.6
; printing object file1.stl id:0 copy 0
G1 X121.75 Y105 F10800
G1 Z1.6 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X128.25 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.8


;WIPE_START
G1 F8640
M73 P76 R0
G1 X124.959 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
M73 P77 R0
G1 Z2 F720
;AFTER_LAYER_CHANGE
;1.8
;CURRENT_Z: 1.8
; printing object file1.stl id:0 copy 0
G1 X121.75 Y105 F10800
G1 Z1.8 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X128.25 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2


;WIPE_START
G1 F8640
M73 P78 R0
G1 X124.959 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z2.2 F720
;AFTER_LAYER_CHANGE
;2
;CURRENT_Z: 2
; printing object file1.stl id:0 copy 0
G1 X121.75 Y105 F10800
G1 Z2 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X128.25 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.2


;WIPE_START
G1 F8640
M73 P79 R0
G1 X124.959 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z2.4 F720
;AFTER_LAYER_CHANGE
;2.2
;CURRENT_Z: 2.2
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
M73 P80 R0
G1 Z2.2 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.4


;WIPE_START
G1 F8640
M73 P81 R0
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z2.6 F720
;AFTER_LAYER_CHANGE
;2.4
;CURRENT_Z: 2.4
; printing object file1.stl id:0 copy 0
G1 X121.75 Y105 F10800
G1 Z2.4 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X128.25 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.6


;WIPE_START
G1 F8640
M73 P82 R0
G1 X124.959 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z2.8 F720
;AFTER_LAYER_CHANGE
;2.6
;CURRENT_Z: 2.6
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
G1 Z2.6 F720
M73 P83 R0
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.8


;WIPE_START
G1 F8640
M73 P84 R0
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z3 F720
;AFTER_LAYER_CHANGE
;2.8
;CURRENT_Z: 2.8
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
G1 Z2.8 F720
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;3


;WIPE_START
G1 F8640
M73 P85 R0
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z3.2 F720
;AFTER_LAYER_CHANGE
;3
;CURRENT_Z: 3
; printing object file1.stl id:0 copy 0
G1 X128.25 Y105 F10800
G1 Z3 F720
M73 P86 R0
G1 E.8 F2100
M204 S800
G1 F900
G1 X121.75 Y105 E.24704
M204 S1000
; stop printing object file1.stl id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
M73 P87 R0
G1 X125.041 Y105 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z3.4 F720
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z4 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z52 F720 ; Move print head further up
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 16.20
; filament used [cm3] = 0.04
; filament used [g] = 0.05
; filament cost = 0.00
; total filament used [g] = 0.05
; total filament cost = 0.00
; estimated printing time (normal mode) = 53s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK2[^.].*/ and nozzle_diameter[0]==0.4"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm OPTIMAL
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM900 K0 ; reset LA\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 40
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 20%
; fill_pattern = cubic
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 2000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 60
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\n;CURRENT_Z: [layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 10000
; machine_max_acceleration_extruding = 2000
; machine_max_acceleration_retracting = 1500
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000
; machine_max_acceleration_y = 9000
; machine_max_acceleration_z = 500
; machine_max_feedrate_e = 120
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 4.5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 200
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 50
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm NORMAL
; printer_model = MK2.5
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK2\n
; printer_settings_id = Original Prusa i3 MK2.5
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 199
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 50
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.11.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
